### ISSUE TITLE
m3u8 builder?

### ISSUE THREAD

**Issue by kaihendry** [videojs/m3u8-parser#20]
How do I get the JSON structure back out as a .m3u8 file?

My use case is that I simply need to add a NAME & RENDITION-ID to each item.

Btw my employers are Brightcove customers.

**Comment by imbcmdth** [comment]
`m3u8-parser` is pretty minimalistic since it's designed around one purpose - enabling HLS playback. If you would like to create an `m3u8-builder` that worked with the same javascript object that `m3u8-parser` generated, that would be awesome and we would be happy to add it to the project as a separate build-target.
